name: Secret Scanning

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
