name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - test
  push:
    branches:
      - test

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
