name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - test
  schedule:
    - cron: '0 12 * * 1'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Start ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'https://silly-capybara-11cf1f.netlify.app/'
          fail_action: false
