name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - test
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'https://silly-capybara-11cf1f.netlify.app/'
          rules_file_name: '.zap/rules.tsv'
          fail_action: false

      - name: Skip Artifact Upload
        run: echo "Skipping artifact upload step."
