name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - test  # Trigger on push to the 'test' branch

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://silly-capybara-11cf1f.netlify.app/'  # URL to scan
          fail_action: false  # Do not fail the workflow on scan failures
          format: 'json'  # Report format (could be json, html, or markdown)

      - name: Upload Scan Report as Artifact
        uses: actions/upload-artifact@v3  # Use a stable version for artifact upload
        with:
          name: zap_scan_reports
          path: |
            report_json.json
            report_md.md
            report_html.html
