name: Simple Nikto Security Test

on:
  push:
    branches:
      - test  # Trigger on push to the 'test' branch

jobs:
  nikto_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nikto
        run: sudo apt-get install -y nikto

      - name: Run Nikto Security Scan and Generate HTML Report
        run: nikto -h https://silly-capybara-11cf1f.netlify.app/ -o nikto_report.html -Format htm  # Generate HTML report

      - name: Display Nikto HTML Report in Logs
        run: cat nikto_report.html