name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - test

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'https://silly-capybara-11cf1f.netlify.app/'
          fail_action: false
          artifact_name: "zapscan"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

